### ISSUE TITLE
Adding a Dockerfile

### ISSUE THREAD

**Issue by kanakmi** [benthecoder/linkedin-visualizer#5]
Hey Ben 👋🏻

I wish to contribute a Dockerfile to this repository to ease out the process of setting up this project in the local system.
The current method is also fine but it is a 4 step process. 
With Docker, It would be a simple 1 step process and would guarantee that the app would run on any operating system that has docker installed and would perform exactly as it did when you tested it.
Let me know if you like this suggestion and I will make a pull request with the dockerfile and will also add the steps to install the app through Docker in the Readme file.

Thanks,
Kanak

**Comment by benthecoder** [comment]
Hey @kanakmi, good idea on adding docker! Thanks for the suggestion and go ahead and send that pull request :)
